"""Create initial tables for users and settings

Revision ID: 46753fd8280f
Revises: 
Create Date: 2025-09-11 14:17:55.824479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46753fd8280f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
