"""add_business_accounts_tables

Revision ID: 75ffbc0a8af2
Revises: bbbceba1fb08
Create Date: 2025-09-11 19:40:20.001335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ffbc0a8af2'
down_revision = 'bbbceba1fb08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
