"""add_business_accounts_tables

Revision ID: a83deb300732
Revises: 75ffbc0a8af2
Create Date: 2025-09-11 19:55:28.315942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83deb300732'
down_revision = '75ffbc0a8af2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
