"""Add settings tables

Revision ID: bbbceba1fb08
Revises: 46753fd8280f
Create Date: 2025-09-11 14:26:34.770745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbceba1fb08'
down_revision = '46753fd8280f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
